name: C CI

on: [push]

jobs:
  build:
    name: Deploy
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout
      - uses: actions/checkout@v1
      - name: CreateDirectory
        run: mkdir build
      - name: Configure
        working-directory: build
        run: cmake ..
      - name: Compile
        working-directory: build
        run: make -j16
  

